services:
  postgres:
    image: postgres:16-alpine
    container_name: eventia_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: eventia
      POSTGRES_PASSWORD: eventia123
      POSTGRES_DB: eventia_db
    ports:
      - "5432:5432"
    volumes:
      - eventia_pg_data:/var/lib/postgresql/data

volumes:
  eventia_pg_data:
